# Generated by Django 4.1.3 on 2022-12-04 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя автора')),
                ('surname', models.CharField(max_length=50, verbose_name='Имя автора')),
                ('cit', models.CharField(max_length=50, verbose_name='Гражданство')),
                ('birthday', models.DateField(verbose_name='Дата рождения автора')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Pub_house',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название издательства')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Издательство',
                'verbose_name_plural': 'Издательства',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название книги')),
                ('num_page', models.IntegerField(verbose_name='Количество страниц')),
                ('seria', models.CharField(max_length=50, null=True, verbose_name='Серия книги')),
                ('id_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.authors')),
                ('id_ph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pub_house')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
